# Generated by Django 5.0.2 on 2024-03-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="course",
            fields=[
                (
                    "CID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("InstructorName", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "SID",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("FirstName", models.CharField(max_length=64)),
                ("LastName", models.CharField(max_length=64)),
                ("SPhoneNumber", models.CharField(max_length=10)),
                (
                    "coures",
                    models.ManyToManyField(
                        blank=True, related_name="students", to="myApp.course"
                    ),
                ),
            ],
        ),
    ]
